SELECT NOME, CURSOPREFERIDO
FROM GAFANHOTOS;

SELECT NOME, ANO FROM CURSOS;

SELECT * FROM GAFANHOTOS;

SELECT GAFANHOTOS.NOME, CURSOS.NOME, CURSOS.ANO
FROM GAFANHOTOS INNER JOIN CURSOS
ON CURSOS.IDCURSO = GAFANHOTOS.CURSOPREFERIDO
ORDER BY GAFANHOTOS.NOME;

-- APELIDOS DE COLUNAS

SELECT g.NOME, c.NOME, c.ANO
FROM GAFANHOTOS AS g INNER JOIN CURSOS AS c
ON c.IDCURSO = g.CURSOPREFERIDO
ORDER BY g.NOME;

-- OUTER JOIN

SELECT g.ID, g.NOME , c.NOME, c.ANO
FROM GAFANHOTOS AS g LEFT OUTER JOIN CURSOS AS c
ON c.IDCURSO = g.CURSOPREFERIDO;

SELECT g.NOME , c.NOME, c.ANO
FROM GAFANHOTOS AS g RIGHT OUTER JOIN CURSOS AS c
ON c.IDCURSO = g.CURSOPREFERIDO;
